#!/bin/bash

echo "=== 准备同步升级到 GitHub ==="
echo ""
echo "修改的文件:"
echo "  buildScript/lib/core/get_source_env.sh"
echo ""
echo "执行以下命令:"
echo ""
echo "# 1. 添加修改的文件"
echo "git add buildScript/lib/core/get_source_env.sh"
echo ""
echo "# 2. 提交修改"
echo "git commit -m \"升级 sing-box 核心到 1.12.19-neko-1\""
echo ""
echo "# 3. 推送到 GitHub"
echo "git push origin main"
echo ""
echo "# 4. 创建 tag 触发自动构建"
echo "git tag v1.0.1"
echo "git push origin v1.0.1"
echo ""
echo "=== 完成后 GitHub Actions 会自动构建 ==="
